// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfT0vduZD3KkLEofHqlZCsv-VVIb-0NKY',
    appId: '1:1056625974316:web:9bd68dba392206219b4589',
    messagingSenderId: '1056625974316',
    projectId: 'link-up-data-987c1',
    authDomain: 'link-up-data-987c1.firebaseapp.com',
    storageBucket: 'link-up-data-987c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0QY2KiMnUcwrAPz4rbTfciGdYP_Mmktc',
    appId: '1:1056625974316:android:a743ed971cc4e7589b4589',
    messagingSenderId: '1056625974316',
    projectId: 'link-up-data-987c1',
    storageBucket: 'link-up-data-987c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkm_bANRCHY0EDEZpHO_PUY1WLDPu5T-Q',
    appId: '1:1056625974316:ios:d71d8c0c6c76d6669b4589',
    messagingSenderId: '1056625974316',
    projectId: 'link-up-data-987c1',
    storageBucket: 'link-up-data-987c1.firebasestorage.app',
    androidClientId: '1056625974316-0bh5j7mjt323p9e2427699dqqehegp63.apps.googleusercontent.com',
    iosClientId: '1056625974316-dqonijhnm892b9t2hfhejq0dp1doveo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeLine',
  );

}